[env:cyd2432s024c]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
  -O3
  -D CORE_DEBUG_LEVEL=1
  -D USER_SETUP_LOADED=1
  -include include/InvectusDisplaySetup.h

lib_deps =
  bblanchon/ArduinoJson@6.21.5
  bodmer/TFT_eSPI@2.5.43
  tzapu/WiFiManager@2.0.17
