[env:cyd2432s024c_diag]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = default.csv
build_flags =
  -O2
